### ISSUE TITLE
Wireless DirectInput

### ISSUE THREAD

**Issue by mcamacho97** [csutorasa/XOutput#15] opened 2018-03-06 16:10 UTC
Hello, I have an Android wireless gamepad that does not use a USB dongle, I only connected it with bluetooth, my computer recognizes all the buttons, however the program does not recognize the mapping of the Axes and Dpads

**Comment by csutorasa** [comment] 2018-03-06 18:36
Hi, I am not sure why this can happen and I do not own a device like that.
I think the possible causes are:

- The DirectInput wrapper, that I am using now (slimDX), was released in January 2012. It may be lacking of some features, that I need, so I am planning to move to a newer wrapper (SharpDX) released in May 2017.
- It is not even a DirectInput device, and I should use Raw Input to get the data from it. Luckily the planned new wrapper supports Raw Input as well.

I am planning to make these changes soon.
If you know why your device is not working, please share it with me.

**Comment by mcamacho97** [comment] 2018-03-06 22:49
I do not know the reason for this error, but https://github.com/joao678/XOutput-XBCD that project recognizes all the buttons, including the d-pads and the axes, but the project seems to be abandoned

**Comment by csutorasa** [comment] 2018-03-06 22:50
Thank you for your response, I will check that repository and try to find the cause.

**Comment by csutorasa** [comment] 2018-03-06 23:23
This project may be abandoned, because the GUI changes are not that huge, and the only feature he was trying to do was not working (stated [here](https://github.com/joao678/XOutput-XBCD/commit/f73c71498f5ef923a4335d788d07d0f64f56cc43)). The only change he did was showing the emulated device, so a unusable duplicate will be shown in the device list.

Other than that change, his repository is based on the https://github.com/Stents-/XOutput, that has the same code as I do for discovering devices (SlimDX and same system calls). Could you try, if you can see your device with this https://github.com/Stents-/XOutput/releases/tag/v0.11?

Soon I will release a version with the more up to date discovery, I hope that will work for you.

**Comment by mcamacho97** [comment] 2018-03-07 02:18
Hi, recently I test my gamepad with this https://github.com/Stents-/XOutput/releases/tag/v0.11 project and my gamepad works too, I hope that your project add compability with my device soon, greetings and good luck 👍

**Comment by csutorasa** [comment] 2018-03-07 21:30
I uploaded the 3.0 version now. There is an option to use all recognizable DirectInput devices (even mice or other devices). I hope that can solve your issue.

**Comment by mcamacho97** [comment] 2018-03-08 14:45
OMG THANKS! The 3.0 version recognize my DirectInput device, I can configure all my buttons, incluiding my d-pads and Axes, thank you very much!

**Comment by csutorasa** [comment] 2018-03-09 09:04
I am glad that it works for you. You are welcome.

**Closed by csutorasa** 2018-03-09 09:04 UTC
Labels: bug
